version: "3.8"

services:
  server:
    container_name: hike_tracker_server
    restart: unless-stopped
    image: ht-server:3.0.0
    build:
      dockerfile: Dockerfile
      context: server
    ports:
      - 3001:3001

  client:
    container_name: hike_tracker_client
    restart: unless-stopped
    image: ht-client:3.0.0
    build:
      dockerfile: Dockerfile
      context: client
    ports:
      - 3000:3000
    depends_on:
      - server
